name: 'Upload Release Asset(s)'
description: 'Upload release assets to an existing release in your repository. Uses the same file search logic as actions/upload-artifact'
author: 'GitHub'
inputs:
  repository:
    description: 'The repository for uploading assets.'
    required: true
  release_id:
    description: 'The release id of repo.'
    required: true
  asset_path:
    description: 'The path to the asset you want to upload'
    required: true
  asset_name:
    description: 'The name of the asset you want to upload'
    required: false
  asset_content_type:
    description: 'The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information. It will auto detect using mime-type if not supplied.'
    required: false
outputs:
  browser_download_url:
    description: 'The URL users can navigate to in order to download the uploaded asset'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
